[2025-01-21 06:55:48,517: INFO: config: PyTorch version 2.5.1 available.]
[2025-01-21 06:58:41,733: INFO: config: PyTorch version 2.5.1 available.]
[2025-01-21 06:59:25,346: INFO: config: PyTorch version 2.5.1 available.]
[2025-01-21 06:59:26,240: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-21 06:59:26,250: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 06:59:26,273: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 06:59:26,274: INFO: common: created directory at: artifacts]
[2025-01-21 06:59:26,275: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-21 06:59:27,213: ERROR: main: HTTP Error 403: Forbidden]
Traceback (most recent call last):
  File "D:\7_projects\End-to-end-Text-Summarizer-main\main.py", line 14, in <module>
    data_ingestion.main()
  File "d:\7_projects\end-to-end-text-summarizer-main\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "d:\7_projects\end-to-end-text-summarizer-main\src\textSummarizer\conponents\data_ingestion.py", line 20, in download_file
    filename, headers = request.urlretrieve(
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\urllib\request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
[2025-01-21 07:05:18,614: INFO: config: PyTorch version 2.5.1 available.]
[2025-01-21 07:05:19,431: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-21 07:05:19,434: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 07:05:19,436: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 07:05:19,437: INFO: common: created directory at: artifacts]
[2025-01-21 07:05:19,437: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-21 07:05:20,361: ERROR: main: HTTP Error 403: Forbidden]
Traceback (most recent call last):
  File "D:\7_projects\End-to-end-Text-Summarizer-main\main.py", line 14, in <module>
    data_ingestion.main()
  File "d:\7_projects\end-to-end-text-summarizer-main\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "d:\7_projects\end-to-end-text-summarizer-main\src\textSummarizer\conponents\data_ingestion.py", line 20, in download_file
    filename, headers = request.urlretrieve(
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\urllib\request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
[2025-01-21 07:19:17,339: INFO: config: PyTorch version 2.5.1 available.]
[2025-01-21 07:19:20,493: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-21 07:19:20,510: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 07:19:20,512: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 07:19:20,513: INFO: common: created directory at: artifacts]
[2025-01-21 07:19:20,513: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-21 07:19:24,593: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
x-amz-id-2: vMHNIyl+YwAXptD/oW6/xpAywSf85UHMHcrqR2LLhrAwH3aDDK6sE+5Al+cbmpQIbXQIlMSJIQYlv47eCYX7/kJoskwxY3JF
x-amz-request-id: NZGTG9C68BHAAK7S
Date: Tue, 21 Jan 2025 01:49:21 GMT
Last-Modified: Tue, 21 Jan 2025 00:57:57 GMT
ETag: "8e8de8d8666735de004076151c68cd8d"
x-amz-server-side-encryption: AES256
Content-Disposition: inline
Accept-Ranges: bytes
Content-Type: application/zip
Content-Length: 7903594
Server: AmazonS3
Connection: close

]
[2025-01-21 07:19:24,740: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-21 07:19:24,741: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-01-21 07:19:24,774: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 07:19:24,776: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 07:19:24,776: INFO: common: created directory at: artifacts]
[2025-01-21 07:19:24,776: INFO: common: created directory at: artifacts/data_validation]
[2025-01-21 07:19:24,777: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-01-21 07:19:24,778: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-01-21 07:19:24,781: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 07:19:24,782: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 07:19:24,782: INFO: common: created directory at: artifacts]
[2025-01-21 07:19:24,783: INFO: common: created directory at: artifacts/data_transformation]
[2025-01-21 07:19:32,426: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-01-21 07:19:32,427: INFO: main: *******************]
[2025-01-21 07:19:32,427: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-01-21 07:19:32,431: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 07:19:32,432: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 07:19:32,433: INFO: common: created directory at: artifacts]
[2025-01-21 07:19:32,433: INFO: common: created directory at: artifacts/model_trainer]
[2025-01-21 07:21:48,567: ERROR: main: Using the `Trainer` with `PyTorch` requires `accelerate>=0.26.0`: Please run `pip install transformers[torch]` or `pip install 'accelerate>=0.26.0'`]
Traceback (most recent call last):
  File "D:\7_projects\End-to-end-Text-Summarizer-main\main.py", line 51, in <module>
    model_trainer.main()
  File "d:\7_projects\end-to-end-text-summarizer-main\src\textSummarizer\pipeline\stage_04_model_trainer.py", line 14, in main
    model_trainer_config.train()
  File "d:\7_projects\end-to-end-text-summarizer-main\src\textSummarizer\conponents\model_trainer.py", line 35, in train
    trainer_args = TrainingArguments(
  File "<string>", line 134, in __init__
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\site-packages\transformers\training_args.py", line 1772, in __post_init__
    self.device
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\site-packages\transformers\training_args.py", line 2294, in device
    return self._setup_devices
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\site-packages\transformers\utils\generic.py", line 62, in __get__
    cached = self.fget(obj)
  File "C:\Users\ADMIN\miniconda3\envs\textsumsum\lib\site-packages\transformers\training_args.py", line 2167, in _setup_devices
    raise ImportError(
ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.26.0`: Please run `pip install transformers[torch]` or `pip install 'accelerate>=0.26.0'`
[2025-01-21 07:27:04,520: INFO: config: PyTorch version 2.5.1 available.]
[2025-01-21 07:27:08,201: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-21 07:27:08,216: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 07:27:08,217: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 07:27:08,217: INFO: common: created directory at: artifacts]
[2025-01-21 07:27:08,217: INFO: common: created directory at: artifacts/data_ingestion]
[2025-01-21 07:27:08,217: INFO: data_ingestion: File already exists of size: ~ 7718 KB]
[2025-01-21 07:27:08,411: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-21 07:27:08,412: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-01-21 07:27:08,415: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 07:27:08,416: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 07:27:08,417: INFO: common: created directory at: artifacts]
[2025-01-21 07:27:08,417: INFO: common: created directory at: artifacts/data_validation]
[2025-01-21 07:27:08,418: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-01-21 07:27:08,418: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-01-21 07:27:08,421: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 07:27:08,423: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 07:27:08,424: INFO: common: created directory at: artifacts]
[2025-01-21 07:27:08,424: INFO: common: created directory at: artifacts/data_transformation]
[2025-01-21 07:27:11,400: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-01-21 07:27:11,400: INFO: main: *******************]
[2025-01-21 07:27:11,400: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-01-21 07:27:11,404: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-01-21 07:27:11,405: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-21 07:27:11,406: INFO: common: created directory at: artifacts]
[2025-01-21 07:27:11,406: INFO: common: created directory at: artifacts/model_trainer]
